package AplikasiPendataan;

import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import net.proteanit.sql.DbUtils;

public class EntriClient extends javax.swing.JInternalFrame {

    public EntriClient() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        radioButton = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        areaCombobox = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jasatransportTxt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        priceTxt = new javax.swing.JTextField();
        agreementCbx = new javax.swing.JCheckBox();
        processButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        mailTxt = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        gotoMainMenubtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        alamatTxt = new javax.swing.JTextArea();
        telpTxt = new javax.swing.JTextField();
        paketComboBox = new javax.swing.JComboBox<>();
        totalPriceTxt = new javax.swing.JTextField();
        newBtn = new javax.swing.JButton();
        dateTxt = new com.toedter.calendar.JDateChooser();
        orderNameTxt = new javax.swing.JTextField();

        jLabel1.setText("Nama Client");

        jLabel2.setText("No. Telp");

        jLabel3.setText("Area (Lokasi Nikah)");

        areaCombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---------------SELECT--------------", "BOGOR", "JAKARTA", "BEKASI" }));
        areaCombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                areaComboboxActionPerformed(evt);
            }
        });

        jLabel5.setText("Biaya Jasa & Transport");

        jLabel6.setText("Paket");

        jasatransportTxt.setEditable(false);
        jasatransportTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel7.setText("Harga Paket");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Total Biaya");

        priceTxt.setEditable(false);
        priceTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        agreementCbx.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        agreementCbx.setText("Setuju");
        agreementCbx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agreementCbxActionPerformed(evt);
            }
        });

        processButton.setText("COUNT");
        processButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processButtonActionPerformed(evt);
            }
        });

        deleteButton.setText("DELETE");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        saveButton.setText("SAVE");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        jLabel4.setText("Alamat");

        jLabel15.setText("E-Mail");

        jLabel16.setText("Tanggal Nikah");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel17.setText("ENTRY CLIENT");

        gotoMainMenubtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        gotoMainMenubtn.setText("OPTION MENU");
        gotoMainMenubtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gotoMainMenubtnActionPerformed(evt);
            }
        });

        alamatTxt.setColumns(20);
        alamatTxt.setRows(5);
        jScrollPane1.setViewportView(alamatTxt);

        paketComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---SELECT---", "CLASSIC", "TRADISIONAL", "MODERN" }));
        paketComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paketComboBoxActionPerformed(evt);
            }
        });

        newBtn.setText("NEW");
        newBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(telpTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(orderNameTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jasatransportTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                    .addComponent(jLabel15)
                                                    .addGap(108, 108, 108))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel16)
                                                    .addGap(62, 62, 62)))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(areaCombobox, 0, 205, Short.MAX_VALUE)
                                                .addComponent(mailTxt)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                                .addComponent(dateTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                    .addComponent(jLabel4))
                                .addGap(55, 55, 55)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(79, 79, 79)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(22, 22, 22))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(paketComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(35, 35, 35))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(processButton, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(39, 39, 39)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(priceTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                                                .addComponent(totalPriceTxt))
                                            .addComponent(gotoMainMenubtn, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(31, 31, 31)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(newBtn)
                                                    .addComponent(agreementCbx))))
                                        .addGap(35, 35, 35))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(317, 317, 317)
                        .addComponent(jLabel17)))
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(orderNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(telpTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(paketComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(priceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel9)
                                .addComponent(totalPriceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel4)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(processButton)
                        .addGap(15, 15, 15)
                        .addComponent(saveButton)
                        .addGap(18, 18, 18)
                        .addComponent(deleteButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(newBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(agreementCbx)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(gotoMainMenubtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel16)
                            .addComponent(dateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(areaCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jasatransportTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void areaComboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_areaComboboxActionPerformed
        switch (areaCombobox.getSelectedIndex()) {
            case 0 ->
                jasatransportTxt.setText("");
            case 1 ->
                jasatransportTxt.setText("350000");
            case 2 ->
                jasatransportTxt.setText("450000");
            default ->
                jasatransportTxt.setText("425000");
        }
    }//GEN-LAST:event_areaComboboxActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        java.util.Date tgl_client = (java.util.Date) this.dateTxt.getDate();
        String name = this.orderNameTxt.getText();
        try {
            Connection c = Database_client.getKoneksi();
            String sql = "Delete from entri Where nama=?";
            PreparedStatement p = (PreparedStatement) c.prepareStatement(sql);
            p.setString(1, name);
            p.executeUpdate();
            p.close();
            JOptionPane.showMessageDialog(this, "Berhasil Hapus Data");
        } catch (SQLException e) {
            System.out.println(e);
        } finally {
        }
        try {
            Connection c = Database_client.getKoneksi();
            Statement s = c.createStatement();
            String sql = "select nama, telp, alamat, email, tgl, area, paket, total from entri";
            ResultSet r = s.executeQuery(sql);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);

        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void processButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processButtonActionPerformed
        try {
            double jasatransportValue = Double.parseDouble(jasatransportTxt.getText());
            double hargapaketValue = Double.parseDouble(priceTxt.getText());
            double totalPriceValue = jasatransportValue + hargapaketValue;

            // Set nilai totalPriceValue ke dalam JTextField totalpriceTxt
            totalPriceTxt.setText(String.valueOf(totalPriceValue));

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Format angka tidak valid");
        }
    }//GEN-LAST:event_processButtonActionPerformed

    private void agreementCbxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agreementCbxActionPerformed
        if (orderNameTxt.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Nama Client Harus Diisi");
            agreementCbx.setSelected(false);
        } else if (telpTxt.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "No. Telp Client Harus Diisi");
            agreementCbx.setSelected(false);
        } else if (alamatTxt.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Alamat Client Harus Diisi");
            agreementCbx.setSelected(false);
        } else if (mailTxt.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Email Client Harus Diisi");
            agreementCbx.setSelected(false);
        } else if (totalPriceTxt.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Tekan COUNT Terlebih Dahulu");
            agreementCbx.setSelected(false);
        } else if (agreementCbx.isSelected() == true) {
            JOptionPane.showMessageDialog(null, "Client Setuju");
            agreementCbx.setSelected(true);
        } else {
            JOptionPane.showMessageDialog(null, "Client Belum Menyetujui");
            agreementCbx.setSelected(false);
        }
    }//GEN-LAST:event_agreementCbxActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        java.util.Date tgl_client = (java.util.Date) this.dateTxt.getDate();
        if (agreementCbx.isSelected() == false) {
            JOptionPane.showMessageDialog(null,
                    "Klik Centang Setuju Untuk Save Data", "Error",
                    JOptionPane.ERROR_MESSAGE);
        } else {
            try {
                String sql = "INSERT INTO entri (nama, telp, alamat, email, tgl, area, paket, total) VALUES (?, ?, ?, ?, ?, ?, ?, ?)";
                Connection conn = (Connection) Database_client.getKoneksi();
                PreparedStatement pst = (PreparedStatement) conn.prepareStatement(sql);

                // Set parameter values
                pst.setString(1, orderNameTxt.getText());
                pst.setString(2, telpTxt.getText());
                pst.setString(3, alamatTxt.getText());
                pst.setString(4, mailTxt.getText());
                pst.setDate(5, new java.sql.Date(tgl_client.getTime()));
                pst.setInt(6, areaCombobox.getSelectedIndex());
                pst.setInt(7, paketComboBox.getSelectedIndex());
                pst.setString(8, totalPriceTxt.getText());

                pst.executeUpdate();
                JOptionPane.showMessageDialog(null, "Berhasil Simpan Data");

            } catch (SQLException ex) {
                Logger.getLogger(EntriClient.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_saveButtonActionPerformed

    private void paketComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paketComboBoxActionPerformed
        switch (paketComboBox.getSelectedIndex()) {
            case 0 ->
                priceTxt.setText("");
            case 1 ->
                priceTxt.setText("550000");
            case 2 ->
                priceTxt.setText("375000");
            default ->
                priceTxt.setText("775000");
        }
    }//GEN-LAST:event_paketComboBoxActionPerformed

    private void gotoMainMenubtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gotoMainMenubtnActionPerformed
        OptionMenu optionMenu = new OptionMenu();
        optionMenu.setVisible(true);
        this.getDesktopPane().add(optionMenu);
        this.dispose();
    }//GEN-LAST:event_gotoMainMenubtnActionPerformed

    private void newBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newBtnActionPerformed
        orderNameTxt.setText("");
        telpTxt.setText("");
        alamatTxt.setText("");
        mailTxt.setText("");
        jasatransportTxt.setText("");
        priceTxt.setText("");
        areaCombobox.setSelectedIndex(0);
        paketComboBox.setSelectedIndex(0);
        dateTxt.setDate(null);
        totalPriceTxt.setText("");
        agreementCbx.setSelected(false);
    }//GEN-LAST:event_newBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox agreementCbx;
    private javax.swing.JTextArea alamatTxt;
    private javax.swing.JComboBox<String> areaCombobox;
    private com.toedter.calendar.JDateChooser dateTxt;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton gotoMainMenubtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jasatransportTxt;
    private javax.swing.JTextField mailTxt;
    private javax.swing.JButton newBtn;
    private javax.swing.JTextField orderNameTxt;
    private javax.swing.JComboBox<String> paketComboBox;
    private javax.swing.JTextField priceTxt;
    private javax.swing.JButton processButton;
    private javax.swing.ButtonGroup radioButton;
    private javax.swing.JButton saveButton;
    private javax.swing.JTextField telpTxt;
    private javax.swing.JTextField totalPriceTxt;
    // End of variables declaration//GEN-END:variables
}
